#ifndef JJMA_HPP
#define JJMA_HPP

#include <map>
#include <string>
#include <filesystem>
#include <vector>
#include <variant>

/*
 * if an id is not present within the 
 * source (essentially the csv file),
 * then we create it.
 * 
 * The id must be an unsigned int
 */
enum jjma_dataTypes {
    ID,     // unsigned int /* auto-incrementing ID column always generated by us */
    INT,    // long
    DOUBLE, // double
    STRING, // std::string
    // BOOL    // boolean
    UNKNOWN // unknown data type
};

std::filesystem::path build_jjma_for_csv(const std::map<std::string, jjma_dataTypes>);
std::map<std::string, jjma_dataTypes> parse_schema(const std::filesystem::path&);
jjma_dataTypes stringToEnum(const std::string&);

#endif /* JJMA_HPP */